### ISSUE TITLE
[Minor] Refresh option

### ISSUE THREAD

**Issue by ThibautSF** [NicolasGrosjean/Translate_helper#13]
Hi,

With Translate Helper v2.2 the refresh option don't refresh the actual project but the DEMO one.

Before F5:
![image](https://user-images.githubusercontent.com/9386581/36807797-10fbdeea-1cc4-11e8-994c-662f3c2693d1.png)

After F5:
![image](https://user-images.githubusercontent.com/9386581/36807825-1fcb833a-1cc4-11e8-94c4-24e156c27b18.png)

**Comment by ThibautSF** [comment]
Little modification, F5/refresh reload the project selected when app was opened.

Example : 
- Last project active PROJ1
- Launch app PROJ1 loaded
- Go to PROJ2 and work
- Try to reload PROJ2 : PROJ1 is loaded

**Comment by NicolasGrosjean** [comment]
Thanks for the bug report
