### ISSUE TITLE
Error selecting CK3 localization folder

### ISSUE THREAD

**Issue by Sourenics** [NicolasGrosjean/Translate_helper#42]
When I select the folder, the console gives the next errors:

`D:\Games\Crusader Kings III\game\localization\english\event_localization\lifestyle\guile\intrigue_temptation_events_2_ l_english.yml was bad named. It doesn't respect format : dir/name_l_language.yml
D:\Games\Crusader Kings III\game\localization\french\event_localization\lifestyle\guile\intrigue_temptation_events_2_ l_french.yml was bad named. It doesn't respect format : dir/name_l_language.yml
D:\Games\Crusader Kings III\game\localization\german\event_localization\lifestyle\guile\intrigue_temptation_events_2_ l_german.yml was bad named. It doesn't respect format : dir/name_l_language.yml
D:\Games\Crusader Kings III\game\localization\korean\event_localization\lifestyle\guile\intrigue_temptation_events_2_ l_korean.yml was bad named. It doesn't respect format : dir/name_l_language.yml
D:\Games\Crusader Kings III\game\localization\languages.yml was bad named. It doesn't respect format : dir/name_l_language.yml
D:\Games\Crusader Kings III\game\localization\russian\event_localization\lifestyle\guile\intrigue_temptation_events_2_ l_russian.yml was bad named. It doesn't respect format : dir/name_l_language.yml
D:\Games\Crusader Kings III\game\localization\simp_chinese\event_localization\lifestyle\guile\intrigue_temptation_events_2_ l_simp_chinese.yml was bad named. It doesn't respect format : dir/name_l_language.yml
D:\Games\Crusader Kings III\game\localization\spanish\event_localization\lifestyle\guile\intrigue_temptation_events_2_ l_spanish.yml was bad named. It doesn't respect format : dir/name_l_language.yml
_english.yml and D:\Games\Crusader Kings III\game\localization\german\custom_localization\de_custom_loc_l_spanish.yml don't exist
_english.yml and D:\Games\Crusader Kings III\game\localization\french\custom_localization\fr_custom_loc_l_spanish.yml don't exist
_english.yml and D:\Games\Crusader Kings III\game\localization\russian\custom_localization\ru_custom_loc_l_spanish.yml don't exist
_english.yml and D:\Games\Crusader Kings III\game\localization\korean\custom_localization\personality_quirks_KR_l_spanish.yml don't exist
_english.yml and D:\Games\Crusader Kings III\game\localization\german\custom_localization\de_custom_loc_extra_l_spanish.yml don't exist`

**Comment by NicolasGrosjean** [comment]
For the files with the *bad named* error, it is because there a space in the name.

There is maybe some errors because some files are missing for some languages, but I am not sure it is not related to the space in the file name.

Say me if you have still issues after replacing the space by underscore.

P.S: Somebody has reported to me that in CK3 (contrary to Imperator Rome ?), it is possible to have the same filename in several directories. It is currently an issue (#41)

**Comment by Sourenics** [comment]
Yes, I reported through steam. On the game localization files, there are some files (don't know how many exactly) but for example there are two `council_l_english.yml` and/or `council_l_spanish.yml`, one in the main localization folder for each language, and another one in the subfolder called `opinions`.

As for the space in the file name, I'm checking ASAP.

**Comment by Sourenics** [comment]
Yes, there are some spaces in the name, you are completly right. But, since these are the game files, if you touch them, you change the checksum. Anyways, is not fault of your awesome APP.

**Comment by Sourenics** [comment]
Also, i noticed that it doesn't matter if I select the localization folder for Stellaris, Imperator: Rome or CK3. Always the same problem with the localization.yml file

Imperator example: `D:\Games\ImperatorRome\game\localization\languages.yml was bad named. It doesn't respect format : dir/name_l_language.yml`
CK3 example: `D:\Games\Crusader Kings III\game\localization\languages.yml was bad named. It doesn't respect format : dir/name_l_language.yml`

**Comment by NicolasGrosjean** [comment]
The *languages.yml* has a structure which is different from the other localization files.

Normally it is not an issue, because you have not to translate it, simply edit it to add a new language if needed.

**Comment by Sourenics** [comment]
Oh I get it. What a facepalm. I have another question, don't know if related, but when translating, If I right-click and select the open source, it opens the english file, but if I click on open destination, it still opens the english file. However, when I start translating, the changes are made on the destination file properly. How is that?

**Comment by NicolasGrosjean** [comment]
I have totally forgotten this functionality, I suppose it will not be too long to fix.

I have opened a new issue for it (#43)

**Comment by NicolasGrosjean** [comment]
@Sourenics I have released a 3.2 version which fix the issues you have reported (thank you for the reporting 👍 ).

I close this issue, do not hesitate to open new issue if you encounter issue with the latest version.
