### ISSUE TITLE
Add Deepl

### ISSUE THREAD

**Issue by Vojtak42** [NicolasGrosjean/Translate_helper#49]
Hello,
Please add option to use Deepl translator instead of google.

**Comment by NicolasGrosjean** [comment]
Hello,
The Deepl API is not free even for small daily usage, that's why I have not set it.

But if you are on Windows, you can use Deepl for Windows inside the Translate Helper, it translates with a simple double Ctrl+C.

**Comment by Vojtak42** [comment]
Thank you for reply.

**Comment by Vojtak42** [comment]
Wouldn't be possible to somehow import .net API?

To use the DeepL .NET Library, you'll need an API authentication key. To get a key, please create an account here. With a DeepL API Free account you can translate up to 500,000 characters/month for free.
Source: https://github.com/DeepLcom/deepl-dotnet

**Comment by NicolasGrosjean** [comment]
I didn't know that DeepL has now a free API plan.

I don't know .Net, but the API can be used with any programming language with HTTP request (like I have done in [this Python project](https://github.com/NicolasGrosjean/DeepL_Paradox)).

I will take a look about it this month.

**Comment by NicolasGrosjean** [comment]
Implemented in the new version.

[Download link](https://steamcommunity.com/linkfilter/?url=https://github.com/NicolasGrosjean/Translate_helper/releases/download/v3.4/TranslateHelper_v3-4.zip)

You can copy some of your config files to avoid to do it again (accepted_loanwords.txt, available_languages.csv, config.xml).

Setup of DeepL :

- [Create a an account on DeepL and subscribe to the Free API](https://www.deepl.com/fr/pro-checkout/account?productId=1200&yearly=false&trial=false)
- Get your API key in [your account page](https://www.deepl.com/fr/account/summary)
- Copy your API key in the file config/deepL_api_key.txt
- Restart the Translate Helper if it runs

@Vojtak42 Do not hesitate to open again this issue if it doesn't work for you.
