### ISSUE TITLE
Update localization files

### ISSUE THREAD

**Issue by Vojtak42** [NicolasGrosjean/Translate_helper#50]
Hello,
wouldn't it be possible to add feature to automate copy of changed and new strings to already translated old files?

**Comment by NicolasGrosjean** [comment]
Hello,

I have already done it in [another projet](https://github.com/NicolasGrosjean/Paradox_localization_utils#apply-diff-all).

**Comment by Vojtak42** [comment]
Hmmm... I think i have tried it already and it havent worked but i'll try it again
