### ISSUE TITLE
[Minor] Recent Project with deleted directory

### ISSUE THREAD

**Issue by ThibautSF** [NicolasGrosjean/Translate_helper#8]
When I try to use "Open Recent" for a project with a deleted directory, the app is partially blocked.

![image](https://user-images.githubusercontent.com/9386581/35200346-b562188a-ff0c-11e7-92eb-e933cb55e295.png)

I can still use "Configuration" menu (make a new project, refresh the actual one or open another) to solve the problem.

**Comment by ThibautSF** [comment]
![image](https://user-images.githubusercontent.com/9386581/35200377-a1bd8f66-ff0d-11e7-8975-86f1cde9493e.png)

Maybe it could ask if we want to modify the options for this project (for example the directory was moved/rename) or do nothing (cancel the action, so stay on the current project)

**Comment by NicolasGrosjean** [comment]
Thanks for feedback.

This issue avoid to launch the application as start as well, it is very problematic.
The users need to change by hand the config file or to create/restore the good directory.
